# ci-build.yaml

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: tensorflow/tensorflow:${{ matrix.version }}
    strategy:
      matrix:
        version: [2.11.0, latest]

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python setup.py bdist_wheel
          python -m pip install dist/* --force-reinstall --no-deps
          python -m pip install flake8 pytest pytest-cov

      - name: Run test
        run: |
          pytest ./tests